"""drop division lab room id shared lab pool

The department has five physical labs (Lab A-E) shared by every division, so a lab is
no longer pinned to a division; the GA picks one from the shared pool per lab session.

Revision ID: 2ef363712bc6
Revises: 722044599067
Create Date: 2026-09-19 17:15:06.742211

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ef363712bc6'
down_revision: str | Sequence[str] | None = '722044599067'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('divisions_lab_room_id_fkey'), 'divisions', type_='foreignkey')
    op.drop_column('divisions', 'lab_room_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('divisions', sa.Column('lab_room_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('divisions_lab_room_id_fkey'), 'divisions', 'classrooms', ['lab_room_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
