"""create division, division_course, lab_batch, timetable and timetable_session tables

Revision ID: 722044599067
Revises: ef3f9e008a22
Create Date: 2026-09-18 23:24:42.355107

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '722044599067'
down_revision: str | Sequence[str] | None = 'ef3f9e008a22'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timetables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=150), nullable=False),
    sa.Column('status', sa.Enum('draft', 'generating', 'published', 'archived', name='timetable_status'), nullable=False),
    sa.Column('algorithm_version', sa.String(length=50), nullable=False),
    sa.Column('generation_params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fitness_score', sa.Float(), nullable=True),
    sa.Column('converged', sa.Boolean(), nullable=False),
    sa.Column('generation_count', sa.Integer(), nullable=True),
    sa.Column('conflict_list', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('divisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('part', sa.Integer(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=True),
    sa.Column('shift', sa.String(length=20), nullable=True),
    sa.Column('group', sa.String(length=10), nullable=True),
    sa.Column('course_scheme_id', sa.Integer(), nullable=True),
    sa.Column('student_count', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(length=150), nullable=False),
    sa.Column('home_room_id', sa.Integer(), nullable=True),
    sa.Column('lab_room_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_scheme_id'], ['course_schemes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['home_room_id'], ['classrooms.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lab_room_id'], ['classrooms.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('program_id', 'part', 'shift', 'group', name='uq_division_program_part_shift_group')
    )
    op.create_index(op.f('ix_divisions_program_id'), 'divisions', ['program_id'], unique=False)
    op.create_table('division_courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('division_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('weekly_theory_periods', sa.Integer(), nullable=False),
    sa.Column('has_lab', sa.Boolean(), nullable=False),
    sa.Column('lab_teacher_id', sa.Integer(), nullable=True),
    sa.Column('weekly_lab_periods', sa.Integer(), nullable=True),
    sa.Column('joint_division_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['division_id'], ['divisions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['joint_division_id'], ['divisions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lab_teacher_id'], ['teachers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('division_id', 'course_id', name='uq_division_course')
    )
    op.create_index(op.f('ix_division_courses_course_id'), 'division_courses', ['course_id'], unique=False)
    op.create_index(op.f('ix_division_courses_division_id'), 'division_courses', ['division_id'], unique=False)
    op.create_table('lab_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('division_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('batch_label', sa.String(length=50), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['division_id'], ['divisions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['classrooms.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lab_batches_division_id'), 'lab_batches', ['division_id'], unique=False)
    op.create_table('timetable_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timetable_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('division_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('day', sa.String(length=3), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('is_lab', sa.Boolean(), nullable=False),
    sa.Column('lab_batch_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['lab_batch_id'], ['lab_batches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['room_id'], ['classrooms.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['timetable_id'], ['timetables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timetable_sessions_timetable_id'), 'timetable_sessions', ['timetable_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timetable_sessions_timetable_id'), table_name='timetable_sessions')
    op.drop_table('timetable_sessions')
    op.drop_index(op.f('ix_lab_batches_division_id'), table_name='lab_batches')
    op.drop_table('lab_batches')
    op.drop_index(op.f('ix_division_courses_division_id'), table_name='division_courses')
    op.drop_index(op.f('ix_division_courses_course_id'), table_name='division_courses')
    op.drop_table('division_courses')
    op.drop_index(op.f('ix_divisions_program_id'), table_name='divisions')
    op.drop_table('divisions')
    op.drop_table('timetables')
    # ### end Alembic commands ###
    # Autogenerate does not clean this up, and leaving it behind makes a
    # later upgrade fail with "type already exists" (same fix as the first migration).
    sa.Enum(name='timetable_status').drop(op.get_bind())
