"""create department, program, classroom, teacher, course_scheme and course tables

Revision ID: ef3f9e008a22
Revises:
Create Date: 2026-09-16 10:09:30.050420

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ef3f9e008a22'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classrooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('type', sa.Enum('lecture', 'lab', 'hall', 'multimedia', name='classroom_type'), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('short_code', sa.String(length=10), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('short_code')
    )
    op.create_table('programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Enum('BS', 'Master', 'MPhil', 'MPhilBioinformatics', 'PhD', 'MScPass',
                               'PGD', name='program_level'), nullable=False),
    sa.Column('display_name', sa.String(length=150), nullable=False),
    sa.Column('total_semesters', sa.Integer(), nullable=True),
    sa.Column('is_schedulable', sa.Boolean(), nullable=False),
    sa.Column('has_shift_split', sa.Boolean(), nullable=False),
    sa.Column('has_pm_pe_split_from_part', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('department_id', 'level', name='uq_program_department_level')
    )
    op.create_index(op.f('ix_programs_department_id'), 'programs', ['department_id'], unique=False)
    op.create_table('course_schemes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('scheme_year', sa.Integer(), nullable=False),
    sa.Column('source_filename', sa.String(length=255), nullable=True),
    sa.Column('file_url', sa.String(length=500), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('program_id', 'scheme_year', name='uq_scheme_program_year')
    )
    op.create_index(op.f('ix_course_schemes_program_id'), 'course_schemes', ['program_id'], unique=False)
    op.create_table('teachers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('designation', sa.String(length=100), nullable=True),
    sa.Column('home_program_id', sa.Integer(), nullable=True),
    sa.Column('max_hours_per_week', sa.Integer(), nullable=True),
    sa.Column('availability', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['home_program_id'], ['programs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teachers_full_name'), 'teachers', ['full_name'], unique=False)
    op.create_index(op.f('ix_teachers_home_program_id'), 'teachers', ['home_program_id'], unique=False)
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scheme_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('credit_hours', sa.Integer(), nullable=True),
    sa.Column('has_lab', sa.Boolean(), nullable=False),
    sa.Column('lab_credit_hours', sa.Integer(), nullable=True),
    sa.Column('min_marks', sa.Integer(), nullable=True),
    sa.Column('max_marks', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scheme_id'], ['course_schemes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scheme_id', 'code', name='uq_course_scheme_code')
    )
    op.create_index(op.f('ix_courses_scheme_id'), 'courses', ['scheme_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_courses_scheme_id'), table_name='courses')
    op.drop_table('courses')
    op.drop_index(op.f('ix_teachers_home_program_id'), table_name='teachers')
    op.drop_index(op.f('ix_teachers_full_name'), table_name='teachers')
    op.drop_table('teachers')
    op.drop_index(op.f('ix_course_schemes_program_id'), table_name='course_schemes')
    op.drop_table('course_schemes')
    op.drop_index(op.f('ix_programs_department_id'), table_name='programs')
    op.drop_table('programs')
    op.drop_table('departments')
    op.drop_table('classrooms')
    # ### end Alembic commands ###
    # Autogenerate does not clean these up, and leaving them behind makes a
    # later upgrade fail with "type already exists".
    sa.Enum(name='program_level').drop(op.get_bind())
    sa.Enum(name='classroom_type').drop(op.get_bind())
